[project]
name = "emilybot"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
  "discord-py>=2.5.2",
]

[dependency-groups]
dev = [
  "pyright>=1.1.403",
]

[tool.pyright]
typeCheckingMode = "strict"
