"""
This type stub file was generated by pyright.
"""

from .database import JsonDB, JsonSerializer
from .exceptions import JsonDBException

"""Simple JSON Database - A lightweight JSON-based database for Python applications."""
__version__ = ...
__all__ = ["JsonDB", "JsonSerializer", "JsonDBException"]

def main() -> None:
    """Entry point for the CLI."""
    ...
