name: test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo MISE_ENV=ci >> "$GITHUB_ENV"
          rm .env.yaml  # so that mise doesn't even try to decrypt it
      - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac
      - run: "mise run --jobs=1 check ::: test:js ::: test:python"
